// src/views/TranslateView.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { ArrowDown, Delete, Setting } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { emit, listen, type UnlistenFn } from '@tauri-apps/api/event'
import { getCurrentWindow } from '@tauri-apps/api/window'
import { translate, loadSettings, saveSetting } from '../api/deepseek'
import HistoryDialog from '../components/HistoryDialog.vue'
import PromptDialog from '../components/PromptDialog.vue'

const winId = getCurrentWindow().label
let unlistenSync: UnlistenFn | null = null

const DEFAULT_PROMPT = '你是一名专业翻译。将以下文本从{source}翻译成{target}。只返回翻译结果，不要添加任何解释、注释或引号。'

const languages = [
  { label: '自动检测', value: 'auto' },
  { label: '中文', value: 'Chinese' }, { label: 'English', value: 'English' },
  { label: '한국어', value: 'Korean' }, { label: '日本語', value: 'Japanese' },
  { label: 'Deutsch', value: 'German' }, { label: 'Français', value: 'French' },
  { label: 'العربية', value: 'Arabic' },
]

const modelOptions = [
  { label: 'deepseek-v4-flash', value: 'deepseek-v4-flash' },
  { label: 'deepseek-v4-pro', value: 'deepseek-v4-pro' },
  { label: '自定义', value: 'custom' },
]

const apiKey = ref('')
const model = ref('deepseek-v4-flash')
const customModel = ref('')
const systemPrompt = ref(DEFAULT_PROMPT)
const showSettings = ref(false)
const effectiveModel = computed(() => model.value === 'custom' ? (customModel.value || 'deepseek-v4-flash') : model.value)

const sourceText = ref('')
const sourceLang = ref('auto')
const targetLang = ref('English')
const result = ref('')
const translating = ref(false)
const errorMsg = ref('')

const showPromptDialog = ref(false)
const showHistory = ref(false)
const historyDialogRef = ref<InstanceType<typeof HistoryDialog> | null>(null)

onMounted(async () => {
  try {
    const settings = await loadSettings()
    if (settings.api_key) apiKey.value = settings.api_key
    if (settings.model) model.value = settings.model
    if (settings.custom_model) customModel.value = settings.custom_model
    if (settings.system_prompt) systemPrompt.value = settings.system_prompt
    unlistenSync = await listen<{ from: string; sourceText: string; result: string }>('translate-sync', (e) => {
      if (e.payload.from === winId) return
      sourceText.value = e.payload.sourceText
      result.value = e.payload.result
    })
    // Settings sync: update in-memory values when other window saves
    const unlistenSettings = await listen<{ from: string; apiKey: string; model: string; customModel: string; systemPrompt: string }>('settings-sync', (s) => {
      if (s.payload.from === winId) return
      apiKey.value = s.payload.apiKey
      model.value = s.payload.model
      customModel.value = s.payload.customModel
      if (s.payload.systemPrompt) systemPrompt.value = s.payload.systemPrompt
    })
    onUnmounted(() => unlistenSettings())
    // When tray switches: source window broadcasts; target window picks it up
    const unlistenSwitch = await listen<string>('switch-sync', (e) => {
      if (e.payload === winId) {
        // I'm the source → broadcast my state to all windows
        syncOut()
      } else {
        // I'm the target → clear local state, source's syncOut will fill it
        sourceText.value = ''
        result.value = ''
        errorMsg.value = ''
      }
    })
    onUnmounted(() => unlistenSwitch())
  } catch (e) { ElMessage.error('加载设置失败: ' + String(e)) }
})

onUnmounted(() => { unlistenSync?.() })

// Explicit sync — only on clear/translate/copy + tray switch
function syncOut() {
  emit('translate-sync', { from: winId, sourceText: sourceText.value, result: result.value })
}

async function handleSaveSettings() {
  try {
    await saveSetting('api_key', apiKey.value)
    await saveSetting('model', model.value)
    await saveSetting('custom_model', customModel.value)
    await saveSetting('system_prompt', systemPrompt.value)
    ElMessage.success('设置已保存')
    emit('settings-sync', { from: winId, apiKey: apiKey.value, model: model.value, customModel: customModel.value, systemPrompt: systemPrompt.value })
  } catch (e) { ElMessage.error('保存失败: ' + String(e)) }
}

function swapLanguages() {
  if (sourceLang.value === 'auto') return
  [sourceLang.value, targetLang.value] = [targetLang.value, sourceLang.value]
}

async function doTranslate() {
  if (!apiKey.value.trim()) { ElMessageBox.alert('请先在翻译设置中配置 DeepSeek API Key', '提示', { confirmButtonText: '确定' }); return }
  if (!sourceText.value.trim()) { ElMessageBox.alert('请输入要翻译的文本', '提示', { confirmButtonText: '确定' }); return }
  if (sourceLang.value !== 'auto' && sourceLang.value === targetLang.value) { ElMessageBox.alert('源语言和目标语言不能相同', '提示', { confirmButtonText: '确定' }); return }
  errorMsg.value = ''; translating.value = true
  try {
    result.value = await translate({ apiKey: apiKey.value.trim(), model: effectiveModel.value, sourceLang: sourceLang.value, targetLang: targetLang.value, text: sourceText.value.trim(), systemPrompt: systemPrompt.value })
    ElMessage.success('翻译完成')
    if (showHistory.value) historyDialogRef.value?.refresh()
  } catch (e) { errorMsg.value = String(e) }
  translating.value = false
}

async function copyResult() {
  if (!result.value) return
  try { await navigator.clipboard.writeText(result.value); ElMessage.success('已复制到剪贴板') } catch { ElMessage.error('复制失败') }
}
</script>

<template>
  <div class="translate-page">
    <el-card class="control-card" shadow="never">
      <div class="control-row">
        <div class="lang-group">
          <span class="label">源语言</span>
          <el-select v-model="sourceLang" size="default" style="width:130px">
            <el-option v-for="l in languages" :key="l.value" :label="l.label" :value="l.value" />
          </el-select>
          <el-button :icon="ArrowDown" circle size="small" :disabled="sourceLang === 'auto'" class="swap" @click="swapLanguages" />
          <span class="label">目标语言</span>
          <el-select v-model="targetLang" size="default" style="width:130px">
            <el-option v-for="l in languages.filter(x => x.value !== 'auto')" :key="l.value" :label="l.label" :value="l.value" />
          </el-select>
        </div>
        <div class="action-group">
          <el-button :icon="Setting" @click="showSettings = !showSettings">{{ showSettings ? '收起设置' : '设置' }}</el-button>
          <el-button type="primary" size="large" :loading="translating" class="do-btn" @click="doTranslate">翻译</el-button>
        </div>
      </div>

      <div v-if="showSettings" class="settings-panel">
        <el-divider />
        <div class="setting-grid">
          <el-input v-model="apiKey" type="password" show-password placeholder="DeepSeek API Key (sk-...)" clearable>
            <template #prepend><span style="font-weight:600">Key</span></template>
          </el-input>
          <el-select v-model="model" style="width:200px">
            <el-option v-for="m in modelOptions" :key="m.value" :label="m.label" :value="m.value" />
          </el-select>
          <el-input v-if="model === 'custom'" v-model="customModel" placeholder="自定义模型名..." style="width:220px" />
          <el-button type="primary" @click="handleSaveSettings">保存设置</el-button>
        </div>
      </div>
    </el-card>

    <div class="text-area-row">
      <div class="text-panel">
        <div class="panel-top">
          <span class="panel-title">源文本</span>
          <el-button v-if="sourceText" :icon="Delete" text size="small" @click="sourceText = ''">清空</el-button>
        </div>
        <el-input v-model="sourceText" type="textarea" placeholder="输入要翻译的文本..." class="ta-input" />
      </div>
      <div class="text-panel">
        <div class="panel-top">
          <span class="panel-title">翻译结果</span>
          <div class="panel-actions">
            <el-button v-if="result" text size="small" @click="copyResult">复制</el-button>
            <el-button v-if="result" text size="small" @click="result = ''; errorMsg = ''">清空</el-button>
          </div>
        </div>
        <el-input :model-value="errorMsg ? '' : result" type="textarea" readonly placeholder="翻译结果将显示在这里" class="ta-input result-ta" />
        <el-alert v-if="errorMsg" :title="errorMsg" type="error" show-icon :closable="false" style="margin-top:6px" />
      </div>
    </div>

    <div class="bottom-bar">
      <el-button text @click="showPromptDialog = true">提示词</el-button>
      <el-button text @click="showHistory = true">翻译历史</el-button>
    </div>

    <PromptDialog v-model="showPromptDialog" :system-prompt="systemPrompt" @update:system-prompt="systemPrompt = $event" />
    <HistoryDialog ref="historyDialogRef" v-model="showHistory" />
  </div>
</template>

<style scoped>
.translate-page { height: 100%; display: flex; flex-direction: column; gap: 12px; overflow: hidden; }

.control-card { flex-shrink: 0; }

.control-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  flex-wrap: wrap;
}

.lang-group { display: flex; align-items: center; gap: 8px; }

.label { font-size: 13px; color: var(--el-text-color-secondary); white-space: nowrap; }

.swap { flex-shrink: 0; }

.action-group { display: flex; align-items: center; gap: 8px; }

.do-btn { min-width: 90px; font-weight: 600; letter-spacing: 2px; }

.settings-panel { margin-top: 4px; }

.setting-grid { display: flex; gap: 10px; align-items: center; flex-wrap: wrap; }

.text-area-row {
  flex: 1;
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 14px;
  min-height: 0;
  overflow: hidden;
}

.text-panel { display: flex; flex-direction: column; gap: 6px; min-height: 0; overflow: hidden; }

.panel-top { display: flex; justify-content: space-between; align-items: center; flex-shrink: 0; }

.panel-title { font-size: 14px; font-weight: 600; color: var(--el-text-color-primary); }

.panel-actions { display: flex; gap: 2px; }

.ta-input { flex: 1; min-height: 0; }

.ta-input :deep(.el-textarea),
.ta-input :deep(.el-textarea__inner) {
  height: 100% !important;
  resize: none !important;
}

.ta-input :deep(.el-textarea__inner) {
  border-radius: 8px;
  font-size: 14px;
  line-height: 1.7;
}

.result-ta :deep(.el-textarea__inner) {
  background: #0d1a1a !important;
  color: var(--cyber-green) !important;
  border-color: rgba(0, 255, 65, 0.15) !important;
}

.bottom-bar { text-align: center; flex-shrink: 0; }
</style>

// src/views/TranslateView.tsx
import { useState, useEffect, useRef } from 'react'
import { getCurrentWindow } from '@tauri-apps/api/window'
import { emit, listen, type UnlistenFn } from '@tauri-apps/api/event'
import {
  Button,
  Dropdown,
  Option,
  Input,
  Textarea,
  Toast,
  ToastTitle,
  useToastController,
  makeStyles,
  tokens,
} from '@fluentui/react-components'
import {
  ArrowSortRegular,
  DeleteRegular,
  SettingsRegular,
  MicRegular,
  HistoryRegular,
} from '@fluentui/react-icons'
import { translate, loadSettings, saveSetting } from '../api/deepseek'
import HistoryDialog from '../components/HistoryDialog'
import PromptDialog from '../components/PromptDialog'

const winId = getCurrentWindow().label

const DEFAULT_PROMPT = '你是一名专业翻译。将以下文本从{source}翻译成{target}。只返回翻译结果，不要添加任何解释、注释或引号。'

const languages = [
  { label: '自动检测', value: 'auto' },
  { label: '中文', value: 'Chinese' },
  { label: 'English', value: 'English' },
  { label: '한국어', value: 'Korean' },
  { label: '日本語', value: 'Japanese' },
  { label: 'Deutsch', value: 'German' },
  { label: 'Français', value: 'French' },
  { label: 'العربية', value: 'Arabic' },
]

const modelOptions = [
  { label: 'deepseek-v4-flash', value: 'deepseek-v4-flash' },
  { label: 'deepseek-v4-pro', value: 'deepseek-v4-pro' },
  { label: '自定义', value: 'custom' },
]

const useStyles = makeStyles({
  page: { height: '100%', display: 'flex', flexDirection: 'column', gap: '12px', overflow: 'hidden' },
  controlRow: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    gap: '8px', padding: '12px 14px',
    border: `1px solid ${tokens.colorNeutralStroke1}`, borderRadius: '8px',
  },
  langGroup: { display: 'flex', alignItems: 'center', gap: '4px', flexShrink: 0 },
  label: { fontSize: '12px', color: tokens.colorNeutralForeground3, whiteSpace: 'nowrap' },
  actionGroup: { display: 'flex', alignItems: 'center', gap: '6px', flexShrink: 0, whiteSpace: 'nowrap' },
  settingsPanel: { marginTop: '8px' },
  settingGrid: { display: 'flex', gap: '10px', alignItems: 'center', flexWrap: 'wrap', marginTop: '8px' },
  textRow: {
    flex: 1, display: 'grid', gridTemplateColumns: '1fr 1fr',
    gap: '14px', minHeight: 0, overflow: 'hidden',
  },
  textPanel: { display: 'flex', flexDirection: 'column', gap: '6px', minHeight: 0, overflow: 'hidden' },
  panelTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexShrink: 0 },
  panelTitle: { fontSize: '14px', fontWeight: 600, color: tokens.colorNeutralForeground1 },
  panelActions: { display: 'flex', gap: '2px' },
  taInput: { flex: 1, minHeight: 0 },
  alert: {
    marginTop: '6px',
    backgroundColor: tokens.colorStatusDangerBackground1,
    border: `1px solid ${tokens.colorStatusDangerBorder1}`,
    borderRadius: '6px',
    padding: '8px 12px',
    color: tokens.colorStatusDangerForeground1,
    fontSize: '13px',
  },
  bottomBar: { textAlign: 'center', flexShrink: 0 },
})

export default function TranslateView() {
  const styles = useStyles()
  const { dispatchToast } = useToastController()

  const [apiKey, setApiKey] = useState('')
  const [model, setModel] = useState('deepseek-v4-flash')
  const [customModel, setCustomModel] = useState('')
  const [systemPrompt, setSystemPrompt] = useState(DEFAULT_PROMPT)
  const [showSettings, setShowSettings] = useState(false)
  const effectiveModel = model === 'custom' ? (customModel || 'deepseek-v4-flash') : model

  const [sourceText, setSourceText] = useState('')
  const [sourceLang, setSourceLang] = useState('auto')
  const [targetLang, setTargetLang] = useState('English')
  const [result, setResult] = useState('')
  const [translating, setTranslating] = useState(false)
  const [errorMsg, setErrorMsg] = useState('')

  const [showPrompt, setShowPrompt] = useState(false)
  const [showHistory, setShowHistory] = useState(false)

  // Refs for latest values (same as Vue refs)
  const sourceTextRef = useRef(sourceText)
  const resultRef = useRef(result)
  sourceTextRef.current = sourceText
  resultRef.current = result

  // syncOut: emit current state (exactly like Vue)
  function syncOut() {
    emit('translate-sync', { from: winId, sourceText: sourceTextRef.current, result: resultRef.current })
  }

  useEffect(() => {
    let unlistenSync: UnlistenFn | null = null
    let unlistenSwitch: UnlistenFn | null = null

    async function setup() {
      try {
        const settings = await loadSettings()
        if (settings.api_key) setApiKey(settings.api_key)
        if (settings.model) setModel(settings.model)
        if (settings.custom_model) setCustomModel(settings.custom_model)
        if (settings.system_prompt) setSystemPrompt(settings.system_prompt)
      } catch (e) {
        dispatchToast(<Toast><ToastTitle>{'加载设置失败: ' + String(e)}</ToastTitle></Toast>, { intent: 'error' })
      }

      // Listen for sync from other window
      unlistenSync = await listen<{ from: string; sourceText: string; result: string }>('translate-sync', (e) => {
        if (e.payload.from === winId) return
        setSourceText(e.payload.sourceText)
        setResult(e.payload.result)
      })

      // Listen for settings sync
      const unlistenSettings = await listen<{ from: string; apiKey: string; model: string; customModel: string; systemPrompt: string }>('settings-sync', (s) => {
        if (s.payload.from === winId) return
        setApiKey(s.payload.apiKey)
        setModel(s.payload.model)
        setCustomModel(s.payload.customModel)
        if (s.payload.systemPrompt) setSystemPrompt(s.payload.systemPrompt)
      })

      // When tray switches: source broadcasts, target clears
      unlistenSwitch = await listen<string>('switch-sync', (e) => {
        if (e.payload === winId) {
          syncOut()
        } else {
          setSourceText('')
          setResult('')
          setErrorMsg('')
        }
      })

      return () => { unlistenSettings() }
    }

    const cleanup = setup()
    return () => { cleanup.then(fn => fn?.()); unlistenSync?.(); unlistenSwitch?.() }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  async function handleSaveSettings() {
    try {
      await saveSetting('api_key', apiKey)
      await saveSetting('model', model)
      await saveSetting('custom_model', customModel)
      await saveSetting('system_prompt', systemPrompt)
      dispatchToast(<Toast><ToastTitle>设置已保存</ToastTitle></Toast>, { intent: 'success' })
      emit('settings-sync', { from: winId, apiKey, model, customModel, systemPrompt })
    } catch (e) {
      dispatchToast(<Toast><ToastTitle>{'保存失败: ' + String(e)}</ToastTitle></Toast>, { intent: 'error' })
    }
  }

  async function doTranslate() {
    if (!apiKey.trim()) {
      dispatchToast(<Toast><ToastTitle>请先配置 DeepSeek API Key</ToastTitle></Toast>, { intent: 'warning' })
      return
    }
    if (!sourceText.trim()) {
      dispatchToast(<Toast><ToastTitle>请输入要翻译的文本</ToastTitle></Toast>, { intent: 'warning' })
      return
    }
    if (sourceLang !== 'auto' && sourceLang === targetLang) {
      dispatchToast(<Toast><ToastTitle>源语言和目标语言不能相同</ToastTitle></Toast>, { intent: 'warning' })
      return
    }
    setErrorMsg('')
    setTranslating(true)
    try {
      const res = await translate({
        apiKey: apiKey.trim(), model: effectiveModel,
        sourceLang, targetLang, text: sourceText.trim(), systemPrompt,
      })
      setResult(res)
      dispatchToast(<Toast><ToastTitle>翻译完成</ToastTitle></Toast>, { intent: 'success' })
    } catch (e) {
      setErrorMsg(String(e))
    }
    setTranslating(false)
  }

  async function copyResult() {
    if (!result) return
    try {
      await navigator.clipboard.writeText(result)
      dispatchToast(<Toast><ToastTitle>已复制到剪贴板</ToastTitle></Toast>, { intent: 'success' })
    } catch {
      dispatchToast(<Toast><ToastTitle>复制失败</ToastTitle></Toast>, { intent: 'error' })
    }
  }

  function swapLanguages() {
    if (sourceLang === 'auto') return
    const src = sourceLang
    const tgt = targetLang
    setSourceLang(tgt)
    setTargetLang(src)
  }

  return (
    <div className={styles.page}>
      <div className={styles.controlRow}>
        <div className={styles.langGroup}>
          <span className={styles.label}>源语言</span>
          <Dropdown value={sourceLang} onOptionSelect={(_, d) => setSourceLang(d.optionValue!)} style={{ width: '110px' }}>
            {languages.map((l) => <Option key={l.value} value={l.value}>{l.label}</Option>)}
          </Dropdown>
          <Button icon={<ArrowSortRegular />} size="small" disabled={sourceLang === 'auto'} onClick={swapLanguages} />
          <span className={styles.label}>目标语言</span>
          <Dropdown value={targetLang} onOptionSelect={(_, d) => setTargetLang(d.optionValue!)} style={{ width: '110px' }}>
            {languages.filter((x) => x.value !== 'auto').map((l) => <Option key={l.value} value={l.value}>{l.label}</Option>)}
          </Dropdown>
        </div>
        <div className={styles.actionGroup}>
          <Button icon={<SettingsRegular />} onClick={() => setShowSettings(!showSettings)}>
            {showSettings ? '收起设置' : '设置'}
          </Button>
          <Button appearance="primary" size="large" disabled={translating} onClick={doTranslate}>
            翻译
          </Button>
        </div>
      </div>

      {showSettings && (
        <div className={styles.settingsPanel}>
          <div className={styles.settingGrid}>
            <Input
              value={apiKey}
              onChange={(_, d) => setApiKey(d.value)}
              type="password"
              placeholder="DeepSeek API Key (sk-...)"
              contentBefore={<span style={{ fontWeight: 600 }}>Key</span>}
            />
            <Dropdown value={model} onOptionSelect={(_, d) => setModel(d.optionValue!)} style={{ width: '200px' }}>
              {modelOptions.map((m) => <Option key={m.value} value={m.value}>{m.label}</Option>)}
            </Dropdown>
            {model === 'custom' && (
              <Input value={customModel} onChange={(_, d) => setCustomModel(d.value)} placeholder="自定义模型名..." style={{ width: '220px' }} />
            )}
            <Button appearance="primary" onClick={handleSaveSettings}>保存设置</Button>
          </div>
        </div>
      )}

      <div className={styles.textRow}>
        <div className={styles.textPanel}>
          <div className={styles.panelTop}>
            <span className={styles.panelTitle}>源文本</span>
            {sourceText && (
              <Button icon={<DeleteRegular />} appearance="subtle" size="small" onClick={() => setSourceText('')}>清空</Button>
            )}
          </div>
          <Textarea className={styles.taInput} value={sourceText} onChange={(_, d) => setSourceText(d.value)} placeholder="输入要翻译的文本..." />
        </div>
        <div className={styles.textPanel}>
          <div className={styles.panelTop}>
            <span className={styles.panelTitle}>翻译结果</span>
            <div className={styles.panelActions}>
              {result && <Button appearance="subtle" size="small" onClick={copyResult}>复制</Button>}
              {result && <Button appearance="subtle" size="small" onClick={() => { setResult(''); setErrorMsg('') }}>清空</Button>}
            </div>
          </div>
          <Textarea className={styles.taInput} value={errorMsg ? '' : result} readOnly placeholder="翻译结果将显示在这里" />
          {errorMsg && <div className={styles.alert}>{errorMsg}</div>}
        </div>
      </div>

      <div className={styles.bottomBar}>
        <Button appearance="subtle" icon={<MicRegular />} onClick={() => setShowPrompt(true)}>提示词</Button>
        <Button appearance="subtle" icon={<HistoryRegular />} onClick={() => setShowHistory(true)}>翻译历史</Button>
      </div>

      <PromptDialog open={showPrompt} systemPrompt={systemPrompt} onOpenChange={setShowPrompt} onSystemPromptChange={setSystemPrompt} />
      <HistoryDialog open={showHistory} onOpenChange={setShowHistory} />
    </div>
  )
}
