// src/components/InputHistoryDialog.tsx
import { useState, useEffect, useCallback } from 'react'
import {
  Dialog,
  DialogSurface,
  DialogBody,
  DialogTitle,
  DialogActions,
  Button,
  Checkbox,
  Dropdown,
  Option,
  Spinner,
  Toast,
  ToastTitle,
  useToastController,
  makeStyles,
  tokens,
} from '@fluentui/react-components'
import {
  DeleteRegular,
  ArrowSyncRegular,
  ArrowSortDownRegular,
  ArrowSortUpRegular,
  CopyRegular,
} from '@fluentui/react-icons'
import { getInputHistory, getInputHistoryCount, deleteInputHistory, type InputRecord } from '../api/deepseek'

const useStyles = makeStyles({
  toolbar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '10px',
    paddingBottom: '10px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    flexWrap: 'wrap',
    gap: '8px',
  },
  toolbarLeft: { display: 'flex', alignItems: 'center', gap: '10px' },
  toolbarRight: { display: 'flex', alignItems: 'center', gap: '6px' },
  sortBtn: {
    cursor: 'pointer',
    padding: '4px',
    borderRadius: '4px',
    color: tokens.colorNeutralForeground4,
    transition: 'all 0.15s',
  },
  sortBtnActive: { color: tokens.colorBrandForeground1 },
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    maxHeight: '50vh',
    overflowY: 'auto',
    minHeight: '100px',
  },
  item: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    padding: '8px 12px',
    background: tokens.colorNeutralBackground4,
    borderRadius: '8px',
  },
  check: { flexShrink: 0, marginTop: '4px' },
  body: { flex: 1, minWidth: 0 },
  meta: { display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' },
  time: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground4,
    fontFamily: "'JetBrains Mono', Consolas, monospace",
  },
  text: {
    margin: 0,
    padding: '8px 10px',
    background: '#1a1a2e',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    borderRadius: '6px',
    fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace",
    fontSize: '12px',
    lineHeight: 1.55,
    color: '#c0c0d8',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-all',
    maxHeight: '200px',
    overflowY: 'auto',
    cursor: 'pointer',
    transition: 'border-color 0.15s',
  },
  empty: { textAlign: 'center', color: tokens.colorNeutralForeground4, padding: '50px 0', fontSize: '14px' },
  pager: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginTop: '14px',
    paddingTop: '10px',
    borderTop: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  pages: { display: 'flex', alignItems: 'center', gap: '2px' },
  pageInfo: { fontSize: '13px', color: tokens.colorNeutralForeground2, padding: '0 8px' },
  total: { fontSize: '12px', color: tokens.colorNeutralForeground4, marginLeft: 'auto' },
  copyBtn: { opacity: 0, transition: 'opacity 0.15s' },
})

const pageSizes = [5, 10, 20]

interface InputHistoryDialogProps {
  open: boolean
  tool: string
  onOpenChange: (open: boolean) => void
  onUseText: (text: string) => void
}

export default function InputHistoryDialog({
  open,
  tool,
  onOpenChange,
  onUseText,
}: InputHistoryDialogProps) {
  const styles = useStyles()
  const { dispatchToast } = useToastController()

  const [records, setRecords] = useState<InputRecord[]>([])
  const [total, setTotal] = useState(0)
  const [selectedIds, setSelectedIds] = useState<Set<number>>(new Set())
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(5)
  const [sortDesc, setSortDesc] = useState(true)
  const [loading, setLoading] = useState(false)

  const totalPages = Math.max(1, Math.ceil(total / pageSize))
  const allSelected = records.length > 0 && records.every((r) => selectedIds.has(r.id))
  const anySelected = selectedIds.size > 0

  function formatTime(dt: string) {
    if (!dt) return ''
    const d = dt.replace('T', ' ').replace('Z', '')
    return d.length >= 19 ? d.substring(0, 19) : d
  }

  async function copyItem(text: string) {
    try {
      await navigator.clipboard.writeText(text)
      dispatchToast(<Toast><ToastTitle>已复制</ToastTitle></Toast>, { intent: 'success' })
    } catch {
      dispatchToast(<Toast><ToastTitle>复制失败</ToastTitle></Toast>, { intent: 'error' })
    }
  }

  function toggleSelect(id: number) {
    setSelectedIds((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  function toggleAll() {
    setSelectedIds(allSelected ? new Set() : new Set(records.map((r) => r.id)))
  }

  async function loadTotal() {
    setTotal(await getInputHistoryCount(tool))
  }

  async function loadPage() {
    setLoading(true)
    try {
      const maxPage = Math.max(1, Math.ceil(total / pageSize))
      const p = page > maxPage ? maxPage : page
      if (p !== page) setPage(p)
      setRecords(await getInputHistory(tool, (p - 1) * pageSize, pageSize, sortDesc))
      setSelectedIds(new Set())
    } catch (e) {
      dispatchToast(<Toast><ToastTitle>{'加载失败: ' + String(e)}</ToastTitle></Toast>, { intent: 'error' })
    }
    setLoading(false)
  }

  async function fullReload() {
    await loadTotal()
    await loadPage()
  }

  async function goPage(p: number) {
    if (p < 1 || p > totalPages) return
    setPage(p)
  }

  async function refresh() {
    setPage(1)
    await fullReload()
  }

  async function deleteSelected() {
    if (selectedIds.size === 0) return
    try {
      await deleteInputHistory(tool, [...selectedIds])
      setTotal(await getInputHistoryCount(tool))
      setSelectedIds(new Set())
      await loadPage()
    } catch {}
  }

  async function deleteAll() {
    try {
      await deleteInputHistory(tool, [])
      setPage(1)
      setTotal(0)
      setRecords([])
      setSelectedIds(new Set())
    } catch {}
  }

  function useRecord(text: string) {
    onUseText(text)
    onOpenChange(false)
  }

  const handleOpen = useCallback(() => {
    setPage(1)
    setSelectedIds(new Set())
    fullReload()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (open) handleOpen()
  }, [open, handleOpen])

  useEffect(() => {
    if (open) { loadPage() }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, pageSize, sortDesc])

  return (
    <Dialog open={open} onOpenChange={(_, data) => onOpenChange(data.open)}>
      <DialogSurface>
        <DialogBody>
          <DialogTitle>输入历史</DialogTitle>

          <div className={styles.toolbar}>
            <div className={styles.toolbarLeft}>
              <Checkbox
                checked={allSelected}
                indeterminate={anySelected && !allSelected}
                onChange={toggleAll}
                label="全选"
              />
              {anySelected && (
                <Button
                  icon={<DeleteRegular />}
                  size="small"
                  appearance="primary"
                  onClick={deleteSelected}
                >
                  删除({selectedIds.size})
                </Button>
              )}
            </div>
            <div className={styles.toolbarRight}>
              <span
                className={`${styles.sortBtn} ${sortDesc ? styles.sortBtnActive : ''}`}
                onClick={() => setSortDesc(!sortDesc)}
                title="排序"
              >
                {sortDesc ? <ArrowSortDownRegular fontSize={16} /> : <ArrowSortUpRegular fontSize={16} />}
              </span>
              <Button
                icon={<ArrowSyncRegular />}
                size="small"
                appearance="subtle"
                disabled={loading}
                onClick={refresh}
              >
                刷新
              </Button>
              <Button size="small" appearance="subtle" onClick={deleteAll}>
                清空全部
              </Button>
            </div>
          </div>

          <div className={styles.list}>
            {loading ? (
              <Spinner />
            ) : records.length === 0 ? (
              <div className={styles.empty}>暂无记录（双击可回填）</div>
            ) : (
              records.map((item) => (
                <div key={item.id} className={styles.item}>
                  <Checkbox
                    className={styles.check}
                    checked={selectedIds.has(item.id)}
                    onChange={() => toggleSelect(item.id)}
                  />
                  <div className={styles.body}>
                    <div className={styles.meta}>
                      <span className={styles.time}>{formatTime(item.created_at)}</span>
                      <Button
                        className={styles.copyBtn}
                        icon={<CopyRegular />}
                        appearance="subtle"
                        size="small"
                        onClick={() => copyItem(item.input_text)}
                        title="复制"
                      />
                    </div>
                    <pre className={styles.text} onDoubleClick={() => useRecord(item.input_text)}>
                      {item.input_text}
                    </pre>
                  </div>
                </div>
              ))
            )}
          </div>

          <div className={styles.pager}>
            <Dropdown
              value={pageSize}
              onOptionSelect={(_, data) => setPageSize(Number(data.optionValue))}
              style={{ width: '80px' }}
              size="small"
            >
              {pageSizes.map((s) => (
                <Option key={s} value={String(s)}>
                  {s}条/页
                </Option>
              ))}
            </Dropdown>
            <div className={styles.pages}>
              <Button size="small" appearance="subtle" disabled={page <= 1} onClick={() => goPage(1)}>
                «
              </Button>
              <Button size="small" appearance="subtle" disabled={page <= 1} onClick={() => goPage(page - 1)}>
                ‹
              </Button>
              <span className={styles.pageInfo}>
                {page} / {totalPages}
              </span>
              <Button
                size="small"
                appearance="subtle"
                disabled={page >= totalPages}
                onClick={() => goPage(page + 1)}
              >
                ›
              </Button>
              <Button
                size="small"
                appearance="subtle"
                disabled={page >= totalPages}
                onClick={() => goPage(totalPages)}
              >
                »
              </Button>
            </div>
            <span className={styles.total}>共 {total} 条</span>
          </div>
        </DialogBody>
        <DialogActions>
          <Button appearance="primary" onClick={() => onOpenChange(false)}>
            关闭
          </Button>
        </DialogActions>
      </DialogSurface>
    </Dialog>
  )
}

// src/components/InputHistoryDialog.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { Delete, Refresh, Top, Bottom, CopyDocument } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getInputHistory, getInputHistoryCount, deleteInputHistory, type InputRecord } from '../api/deepseek'

const props = defineProps<{ modelValue: boolean; tool: string }>()
const emit = defineEmits<{ 'update:modelValue': [v: boolean]; 'useText': [text: string] }>()

const records = ref<InputRecord[]>([])
const total = ref(0)
const selectedIds = ref<Set<number>>(new Set())
const page = ref(1)
const pageSize = ref(5)
const sortDesc = ref(true)
const loading = ref(false)

const pageSizes = [5, 10, 20]
const totalPages = computed(() => Math.max(1, Math.ceil(total.value / pageSize.value)))
const allSelected = computed(() => records.value.length > 0 && records.value.every(r => selectedIds.value.has(r.id)))
const anySelected = computed(() => selectedIds.value.size > 0)

async function copyItem(text: string) {
  try { await navigator.clipboard.writeText(text); ElMessage.success('已复制') } catch { ElMessage.error('复制失败') }
}

function formatTime(dt: string) {
  if (!dt) return ''
  const d = dt.replace('T', ' ').replace('Z', '')
  return d.length >= 19 ? d.substring(0, 19) : d
}

function toggleSelect(id: number) {
  const s = new Set(selectedIds.value)
  if (s.has(id)) { s.delete(id) } else { s.add(id) }
  selectedIds.value = s
}
function toggleAll() {
  selectedIds.value = allSelected.value ? new Set() : new Set(records.value.map(r => r.id))
}

async function loadTotal() { total.value = await getInputHistoryCount(props.tool) }

async function loadPage() {
  loading.value = true
  try {
    const maxPage = Math.max(1, Math.ceil(total.value / pageSize.value))
    if (page.value > maxPage) page.value = maxPage
    records.value = await getInputHistory(props.tool, (page.value - 1) * pageSize.value, pageSize.value, sortDesc.value)
    selectedIds.value = new Set()
  } catch (e) { ElMessage.error('加载失败: ' + String(e)) }
  loading.value = false
}

async function fullReload() { await loadTotal(); await loadPage() }
async function goPage(p: number) { if (p >= 1 && p <= totalPages.value) { page.value = p; await loadPage() } }
async function refresh() { page.value = 1; await fullReload() }

async function deleteSelected() {
  if (selectedIds.value.size === 0) return
  try {
    await ElMessageBox.confirm(`确定删除选中的 ${selectedIds.value.size} 条？`, '确认删除', { confirmButtonText: '删除', cancelButtonText: '取消', type: 'warning' })
    await deleteInputHistory(props.tool, [...selectedIds.value])
    total.value = await getInputHistoryCount(props.tool)
    const maxPage = Math.max(1, Math.ceil(total.value / pageSize.value))
    if (page.value > maxPage) page.value = maxPage
    selectedIds.value = new Set()
    await loadPage()
  } catch {}
}

async function deleteAll() {
  try {
    await ElMessageBox.confirm('确定删除所有历史记录？', '确认', { confirmButtonText: '全部删除', cancelButtonText: '取消', type: 'warning' })
    await deleteInputHistory(props.tool, [])
    page.value = 1; total.value = 0; records.value = []; selectedIds.value = new Set()
    await loadPage()
  } catch {}
}

function useRecord(text: string) {
  emit('useText', text)
  emit('update:modelValue', false)
}

watch([pageSize, sortDesc], () => { page.value = 1; fullReload() })

function handleOpen() { page.value = 1; fullReload() }
defineExpose({ refresh })
</script>

<template>
  <el-dialog :model-value="modelValue" @update:model-value="emit('update:modelValue', $event)" @open="handleOpen" title="输入历史" width="80%" top="3vh">
    <div class="itoolbar">
      <div class="itool-left">
        <el-checkbox :model-value="allSelected" :indeterminate="anySelected && !allSelected" @change="toggleAll">全选</el-checkbox>
        <el-button v-if="anySelected" :icon="Delete" size="small" type="danger" plain @click="deleteSelected">删除({{ selectedIds.size }})</el-button>
      </div>
      <div class="itool-right">
        <span class="isort" :class="{ active: sortDesc }" @click="sortDesc = !sortDesc" title="排序">
          <el-icon :size="16"><component :is="sortDesc ? Bottom : Top" /></el-icon>
        </span>
        <el-button :icon="Refresh" size="small" text :loading="loading" @click="refresh">刷新</el-button>
        <el-button size="small" text type="danger" @click="deleteAll">清空全部</el-button>
      </div>
    </div>

    <div class="ilist" v-loading="loading">
      <div v-for="item in records" :key="item.id" class="iitem">
        <el-checkbox :model-value="selectedIds.has(item.id)" class="icheck" @change="toggleSelect(item.id)" />
        <div class="ibody">
          <div class="imeta">
            <span class="itime">{{ formatTime(item.created_at) }}</span>
            <el-button class="icopy" :icon="CopyDocument" text size="small" @click="copyItem(item.input_text)" title="复制" />
          </div>
          <pre class="itext" @dblclick="useRecord(item.input_text)">{{ item.input_text }}</pre>
        </div>
      </div>
      <div v-if="records.length === 0 && !loading" class="iempty">暂无记录（双击可回填）</div>
    </div>

    <div class="ipager">
      <el-select v-model="pageSize" size="small" style="width:80px">
        <el-option v-for="s in pageSizes" :key="s" :label="`${s}条/页`" :value="s" />
      </el-select>
      <div class="ipages">
        <el-button size="small" text :disabled="page <= 1" @click="goPage(1)">«</el-button>
        <el-button size="small" text :disabled="page <= 1" @click="goPage(page - 1)">‹</el-button>
        <span class="iinfo">{{ page }} / {{ totalPages }}</span>
        <el-button size="small" text :disabled="page >= totalPages" @click="goPage(page + 1)">›</el-button>
        <el-button size="small" text :disabled="page >= totalPages" @click="goPage(totalPages)">»</el-button>
      </div>
      <span class="itotal">共 {{ total }} 条</span>
    </div>
  </el-dialog>
</template>

<style scoped>
.itoolbar { display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px; padding-bottom: 10px; border-bottom: 1px solid var(--cyber-border); flex-wrap: wrap; gap: 8px; }
.itool-left { display: flex; align-items: center; gap: 10px; }
.itool-right { display: flex; align-items: center; gap: 6px; }

.isort { cursor: pointer; padding: 4px; border-radius: 4px; color: var(--el-text-color-placeholder); transition: all .15s; }
.isort:hover { color: var(--el-text-color-regular); background: var(--el-fill-color-light); }
.isort.active { color: var(--cyber-cyan); }

.ilist { display: flex; flex-direction: column; gap: 6px; max-height: 50vh; overflow-y: auto; min-height: 100px; }

.iitem { display: flex; align-items: flex-start; gap: 10px; padding: 8px 12px; background: var(--el-fill-color-lighter); border-radius: 8px; }
.icheck { flex-shrink: 0; margin-top: 4px; }
.ibody { flex: 1; min-width: 0; }

.imeta { display: flex; align-items: center; gap: 8px; margin-bottom: 4px; }
.icopy { opacity: 0; transition: opacity .15s; }
.iitem:hover .icopy { opacity: 0.6; }
.iitem:hover .icopy:hover { opacity: 1; }
.itime { font-size: 11px; color: var(--el-text-color-placeholder); font-family: 'JetBrains Mono', Consolas, monospace; }

.itext {
  margin: 0; padding: 8px 10px;
  background: #1a1a2e; border: 1px solid var(--cyber-border); border-radius: 6px;
  font-family: 'JetBrains Mono', 'Fira Code', Consolas, monospace;
  font-size: 12px; line-height: 1.55; color: #c0c0d8;
  white-space: pre-wrap; word-break: break-all;
  max-height: 200px; overflow-y: auto;
  cursor: pointer; transition: border-color .15s;
}

.itext:hover { border-color: var(--cyber-cyan); }

.iempty { text-align: center; color: var(--el-text-color-placeholder); padding: 50px 0; font-size: 14px; }

.ipager { display: flex; align-items: center; gap: 12px; margin-top: 14px; padding-top: 10px; border-top: 1px solid var(--cyber-border); }
.ipages { display: flex; align-items: center; gap: 2px; }
.iinfo { font-size: 13px; color: var(--el-text-color-regular); padding: 0 8px; }
.itotal { font-size: 12px; color: var(--el-text-color-placeholder); margin-left: auto; }
</style>
